### ISSUE TITLE
Random number generator initialization

### ISSUE THREAD

**Issue by michist** [IAIK/pairings_in_c#1]
In file rand.c:
byte CPRNGState[CPRNG_SIZE];		// seed needs to be initialized, for now we assume memory to be initialized randomly

As the variable CPRNGState is located in the bss section it is always initialized with 0

**Comment by tunterluggauer** [comment]
We added an initialization routine for seeding the PRNG in 8e49c4bfb2452abb695c556499ebfb3f2a57e487.
